|id1 precio1 desc1 plan1
id2 precio2 desc2 plan2
id3 precio3 desc3 plan3|

id1:= 1.
precio1:= 800.
desc1:= 'Plan Basic'.
plan1:= Plan CrearPlan:id1 descripcion:desc1 precio:precio1.

id2:= 2.
precio2:= 1500.
desc2:= 'Plan Oro'.
plan2:= Plan CrearPlan:id2 descripcion:desc2 precio:precio2.

id3:= 3.
precio3:= 2100.
desc3:= 'Plan Platinum'.
plan3:= Plan CrearPlan:id3 descripcion:desc3 precio:precio3.

