|id1 nombre1 mail1 usuario1 clave1 tarjeta1 suscripcionOK1 nuevoUsu1
id2 nombre2 mail2 usuario2 clave2 tarjeta2 suscripcionOK2 nuevoUsu2
id3 nombre3 mail3 usuario3 clave3 tarjeta3 suscripcionOK3 nuevoUsu3
id4 nombre4 mail4 usuario4 clave4 tarjeta4 suscripcionOK4 nuevoUsu4
id5 nombre5 mail5 usuario5 clave5 tarjeta5 suscripcionOK5 nuevoUsu5
id6 nombre6 mail6 usuario6 clave6 tarjeta6 suscripcionOK6 nuevoUsu6
id7 nombre7 mail7 usuario7 clave7 tarjeta7 suscripcionOK7 nuevoUsu7|
id1:=1.
nombre1:= 'Martin Rodriguez'.
mail1:= 'mail1@gmail.com'.
usuario1:= 'martinR01'.
clave1:='ClaveMartinR'.
tarjeta1:='4425****8521'.
suscripcionOK1:=true.
nuevoUsu1 := Usuario crearUsuario:id1 nombre:nombre1 mail:mail1 usuario:usuario1 clave:clave1 tarjeta:tarjeta1 suscripcionOK:suscripcionOK1.

id2:=2.
nombre2:= 'David Alvarez'.
mail2:= 'mail2@gmail.com'.
usuario2:= 'davidA02'.
clave2:='ClaveDavidA'.
tarjeta2:='4425****8522'.
suscripcionOK2:=false.
nuevoUsu2 := Usuario crearUsuario:id2 nombre:nombre2 mail:mail2 usuario:usuario2 clave:clave2 tarjeta:tarjeta2 suscripcionOK:suscripcionOK2.

id3:=3.
nombre3:= 'Lucia Benitez'.
mail3:= 'mail3@gmail.com'.
usuario3:= 'luciaB03'.
clave3:='ClaveLuciaB'.
tarjeta3:='4425****8523'.
suscripcionOK3:=true.
nuevoUsu3 := Usuario crearUsuario:id3 nombre:nombre3 mail:mail3 usuario:usuario3 clave:clave3 tarjeta:tarjeta3 suscripcionOK:suscripcionOK3.

id4:=4.
nombre4:= 'Hugo Flores'.
mail4:= 'mail4@gmail.com'.
usuario4:= 'hugoF04'.
clave4:='ClaveHugoF'.
tarjeta4:='4425****8524'.
suscripcionOK4:=true.
nuevoUsu4 := Usuario crearUsuario:id4 nombre:nombre4 mail:mail4 usuario:usuario4 clave:clave4 tarjeta:tarjeta4 suscripcionOK:suscripcionOK4.

id5:=5.
nombre5:= 'Adrian Gonzalez'.
mail5:= 'mail5@gmail.com'.
usuario5:= 'adrianG05'.
clave5:='ClaveAdrianG'.
tarjeta5:='4425****8525'.
suscripcionOK5:=false.
nuevoUsu5 := Usuario crearUsuario:id5 nombre:nombre5 mail:mail5 usuario:usuario5 clave:clave5 tarjeta:tarjeta5 suscripcionOK:suscripcionOK5.

id6:=6.
nombre6:= 'Carla Lopez'.
mail6:= 'mail6@gmail.com'.
usuario6:= 'carlaL06'.
clave6:='ClaveCarlaL'.
tarjeta6:='4425****8526'.
suscripcionOK6:=true.
nuevoUsu6 := Usuario crearUsuario:id6 nombre:nombre6 mail:mail6 usuario:usuario6 clave:clave6 tarjeta:tarjeta6 suscripcionOK:suscripcionOK6.

id7:=7.
nombre7:= 'Pablo Rojas'.
mail7:= 'mail7@gmail.com'.
usuario7:= 'pabloR07'.
clave7:='ClavePabloR'.
tarjeta7:='4425****8527'.
suscripcionOK7:=false.
nuevoUsu7 := Usuario crearUsuario:id7 nombre:nombre7 mail:mail7 usuario:usuario7 clave:clave7 tarjeta:tarjeta7 suscripcionOK:suscripcionOK7.


